### ISSUE TITLE
Zsh syntax + tmux does not work

### ISSUE THREAD

**Issue by SeyZ** [zsh-users/zsh-syntax-highlighting#104]
Zsh syntax highlight works really well if I use Tmux with one window. If I split the window, the second has no syntax highlighting.

Same behavior if I create a new "tab". The first one has syntax highlight, not the second (the new).

**Comment by mhartington** [comment]
A bit of an old issue, but seeing this as well. 
First tmux window works great, but as soon as I create a new window, I have to source my `.zshrc` again in order to have everything work

**Comment by SeyZ** [comment]
:+1:

**Comment by arcan1s** [comment]
BTW I could not reproduce this bug. I have tried to open tmux and split it to several windows and it works fine w\o rereading zshrc

tmux 1.9_a
zsh 5.0.7
zsh-syntax-highlighting 0.2.1

**Comment by mhartington** [comment]
yeah its iffy, sometimes will work without any issues, and other times it will be problematic

**Comment by danielshahaf** [comment]
Sounds like a problem outside zsh-syntax-highlighting — perhaps the homedir is on NFS and trying to fopen() the files fails intermittently. Or maybe the `source zsh-syntax-highlighting.zsh` command is inside some conditional block.

To people seeing the problem: please check if the problem is limited to zsh-syntax-highlighting, or occurs with other `source`d files too.

**Comment by danielshahaf** [comment]
Please reopen if you stlil see the issue.
