### ISSUE TITLE
Doesn't compatiable with vim's quickfix.

### ISSUE THREAD

**Issue by Mizuchi** [zsh-users/zsh-syntax-highlighting#105]
This bug is discussed here:
https://github.com/zsh-users/fizsh/issues/2

I reported this bug in fizsh's issue list. However, the maintainer of fizsh told me that this issue come from upstream, I should report here.

Reproduce the problem:

1. # make sure the shell is fizsh
$ fizsh

2. # create a illegal c++ source file.
$ echo "int main() { illegal c++ program. }" > a.cpp

3. # write a makefile for it
$ echo -e "all:\n\tg++ a.cpp" > makefile

4. # execute :make in vim
$ vim -c "make"

vim should jump to a.cpp and report errors. It works in bash, zsh or fish. However in fizsh, vim reports "No errors" and doesn't jump to a.cpp.

**Comment by danielshahaf** [comment]
@guidovansteen How can it possibly be zsh-syntax-highlighting's fault that Vim fails to run `make`? zsh-syntax-highlighting isn't involved in that at all.

**Comment by guidovansteen** [comment]
> How can it possibly be zsh-syntax-highlighting's fault that Vim fails to run make? 

Thank you for asking. 

This bug was reported more than 2 years ago against an old version of zsh-syntax-highlighting.zsh. At that time Vim would run make, but it would not show the warning. It is likely that this specific version of Zsh-syntax-highlighting.zsh sent some obscure input to vim, causing vim to skip the warning. 

The bug had originally been reported against fizsh, but I found out that it was only triggered by the then actual version of zsh-syntax-highlighting.zsh (which was sourced by fizsh). That is why I referred @Mizuchi to zsh-syntax-highlighting.zsh as the upstream project. My previous comment in this thread was meant to make clear that the bug was not related to other parts fizsh. 

I have just checked the bug, and it appears to have been fixed by some previous zsh-syntax-highlighting.zsh commit. So we might as well close this bug now. 

Thank you for you alertness!
