### ISSUE TITLE
highlight `nice foo`

### ISSUE THREAD

**Issue by anntzer** [zsh-users/zsh-syntax-highlighting#168]
Similarly to #107, which highlights the command after `sudo`, one could highlight the command after `nice`.

**Comment by danielshahaf** [comment]
The problem is options parsing: see 19981ef9eae354ee004cd6b9a54bf07c0a94965c and 3b3a58be9114687d21f03840ebc4c53365d5e604 for an analogous example.

There are many other commands that accept an `execve`-able argument list; some common ones are `env`, `xargs`, and `find ... -exec`.  Perhaps it would be better, instead of hardcoding _N_ separate option parsers, to hook into completion system (issue #10) and ask compsys to identify command words for us?

compsys already solved the "parse `find`'s command line" problem, and I don't want to have to repeat that exercise. ☺

[ That said... if it's possible to support _nice_, or _env_, or any other single utility, in a simple manner without adding lots of twisty codepaths, that might be worthwhile as an interim measure until #10 is fixed ]

**Comment by anntzer** [comment]
Let's add `strace` to the list of affected commands, too.
