### ISSUE TITLE
add plugin to oh-my-zsh plugins

### ISSUE THREAD

**Issue by oryband** [zsh-users/zsh-syntax-highlighting#227]
https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins-Overview

Adding this plugin to oh-my-zsh repo would make it much easier to install - just adding it to the `plugins=(..)` array in `~/.zshrc`.

Yes, this would mean having to update it in that repo every time it gets updated here, but right now I have to manually pull from here every time I want to update.

**Comment by danielshahaf** [comment]
Sounds like you should use `myrepos` or git submodules, to be able to easily upate multiple repositories.

**Comment by oryband** [comment]
why not just add this plugin oh-my-zsh plugins page like most people do?

**Comment by danielshahaf** [comment]
Are you asking to link to z-sy-h from the oh-my-zsh wiki page, or to copy z-sy-h's code to the oh-my-zsh wiki?

**Comment by oryband** [comment]
@danielshahaf i guess you'll have to copy it and keep it updated
you can try and see if they accept submodules, but you'll have to keep it updated as well since they're updated manually

**Comment by danielshahaf** [comment]
First of all, why are you expecting _me_ to do the work?  I don't use oh-my-zsh.  Doing integration work with oh-my-zsh should be driven by people who use oh-my-zsh.  (That's how open source works.)

As to _how_ integration should happen, I strongly prefer that it be based around using z-sy-h as a submodule rather than forking the code.  That's what antigen, zgen, and prezto do (in fact, two of them use z-sy-h as an example in their READMEs and the third has z-sy-h configured in its default `.gitmodules` file).  oh-my-zsh should do the same.

**Comment by danielshahaf** [comment]
... I am trying to be impartial towards these four frameworks since I know none of them very well, but: prezto supports z-sy-h out of the box, and is a fork of oh-my-zsh, so perhaps simply switching your config from oh-my-zsh to prezto would solve your problem.

Again, I'm just thinking out loud, here.

**Comment by oryband** [comment]
@danielshahaf i agree, very well then. i'll find my own way to keep this plugin updated via my preferred plugin framework

thanks!

**Comment by danielshahaf** [comment]
Good luck!
