### ISSUE TITLE
incorrect highlighting of semicolon after background task

### ISSUE THREAD

**Issue by anntzer** [zsh-users/zsh-syntax-highlighting#271]
... i.e.,
```
$ true&; false
```
(the semicolon is highlighted as an error)

**Comment by danielshahaf** [comment]
Hello again!

The semicolon isn't required for backgrounding: `true& false` works as well.

Highlighting it as an error is intentional: <https://github.com/zsh-users/zsh-syntax-highlighting/blob/683f4837a037e35e6a5236020e855fcd262ed48d/highlighters/main/main-highlighter.zsh#L345-L351>.  The rationale behind that decision is that an empty command is probably a typo.

**Comment by anntzer** [comment]
Well, I didn't know that.  In which case I agree with the current behavior, feel free to close this.
