### ISSUE TITLE
highlighting of proposed corrections

### ISSUE THREAD

**Issue by pseyfert** [zsh-users/zsh-syntax-highlighting#323]
Somewhat as a feature request,
can zsh-syntax-highlighting be used to highlight the zsh correction (copied from [here](http://unix.stackexchange.com/questions/266279/highlighting-of-zsh-correction).)

I'm wondering particularly about zsh's autocorrection filename:
![screenshot](http://i.stack.imgur.com/pofXo.png)
i.e. the original wrongly-typed filename and the suggested one are the same in almost all places except for one place (one additional character, one upper case letter accidentially lower case, …). Once the filename is longer than, say, 20 characters the difference is hard to spot.
The example is artificial as tab completion would've done the job (and I can blindly accept the correction w/o proofreading). But there may be other cases where I really want to proofread the suggestion and would appreciate if the suggested change (i.e. only the added 0 in the example) was highlighted in boldface.

EDIT: copied the original post here to make the issue self-contained.

**Comment by danielshahaf** [comment]
> can zsh-syntax-highlighting be used to highlight the zsh correction as asked here.

Please make issues self-contained.  In this case, you're asking for the filename on the `zsh: correct 'foo' to 'bar' [nyae]? []` line to be highlighted.

In short: zsh itself does not make this possible at the moment: `spckword()` (a C function) prints the prompt by the equivalent of `print -rP -- $SPROMPT`, and there doesn't seem to be any prompt escape that could be used to manipulate %r and %R.  I suggest that you ask zsh upstream to replace $SPROMPT by something smarter (e.g., converting the parameter to a zstyle would do, since then the style could be set with `zstyle -e`; or if there were a precorrect() hook, and you could write a hook that hardcodes $SPROMPT to a value that depends on the current values of %r and %R (using `print -rP %r` to get the value)).

In any case, all this stuff happens outside zle, and there's a chance that it'll turn out to be out of scope for z-sy-h.  (But let's keep this issue open for now)

**Comment by danielshahaf** [comment]
Difference from #251: that issue is about the `_correct_word` widget, this issue is about the prompt generated by the `CORRECT` option.

**Comment by danielshahaf** [comment]
> In short: zsh itself does not make this possible at the moment:
> ⋮
> In any case, all this stuff happens outside zle, and there's a chance that it'll turn out to be out of scope for z-sy-h. (But let's keep this issue open for now)

Upstream thread: [workers/38538](http://www.zsh.org/cgi-bin/mla/redirect?WORKERNUMBER=38538)

**Comment by danielshahaf** [comment]
Issue sweep: not implementable without upstream changes; even _with_ those changes assumed implemented, this would require (1) a completely new way of hooking into zsh (because it will not be $BUFFER that we'd be highlighting), and (2) some sort of characterwise diff facility, and there's no particular reason why that should live in z-sy-h itself.  Therefore, closing.  Feel free to reopen if needed.

**Comment by pseyfert** [comment]
That's alright.

In case anybody out there is curious, I gave it a try myself https://github.com/pseyfert/zsh/commit/7c9ffb44d17ab3f70a05bb2f3975b6b025783a64 and realised this can turn out pretty tough (as far as memory serves, my bodge would perform string replacement on SPROMPT twice - once to get %r and %R in, and then to get color sequences therein parsed - and then extra care is needed to ensure percent signs in the original %r and %R don't break things and that the non-%{r,R} part of SPROMPT doesn't get replaced twice …) So I don't think my patch is good for upstreaming or local patching.

**Comment by danielshahaf** [comment]
Your patch is unsuitable for upstreaming for licensing reasons. The issues you identify are not insurmountable — they just necessitate careful use of `${foo/'%'//%%}`.
