### ISSUE TITLE
Prevent widget override

### ISSUE THREAD

**Issue by psprint** [zsh-users/zsh-syntax-highlighting#324]
Widgets are overridden to call _zle_highlight. How can I prevent this from happening when I know a widget doesn't need to trigger highlighting? In my script, with my widget?

I would say this is possible, because `zsh-users/zaw` behaves like if it had accomplished this – it's region_highlight setting doesn't disappear when using cursors. One of first things that _zle_highlight does is resetting region_highlight array. I load z-sy-h after zaw.

**Comment by danielshahaf** [comment]
I'm not sure what zaw does, but there seem to be two separate issues here:

1. Perhaps z-sy-h should _append_ to an already existing `$region_highlight`, rather than discard the existing value.
2. Given that z-sy-h asks to be registered last, having some form of "widgets not to wrap" might be reasonable.  I say "might" because this facility would only be needed in zsh≤5.2 anyway, since ≥5.3 will do away with widget-by-widget wrapping in favour of pre-redraw (#245).

Let's keep this issue about `#2` (feel free to file a separate issue for `#1`).  This should be simple to implement and useful to people running zsh 5.2 or older with latest z-sy-h.  That is likely a common setup, so I'm inclined to support this change.

What would the interface by which people specify which widgets should/shouldn't be wrapped be?
