### ISSUE TITLE
Color values

### ISSUE THREAD

**Issue by Saurav92** [zsh-users/zsh-syntax-highlighting#393]
How to change color values ? I mean how they are related to terminal color palette ? For example in ${ZSH_HIGHLIGHT_STYLES[unknown-token]:=fg=red,bold}, where the color 'red' is defined ? With my gnome terminal color palette it does not display proper color as I changed the color palette. So I want to understand the relation between the color variables you used and the terminal color palette. Can we use 'tput setaf ' to modify color values as it has direct relation with gnome terminal color palette where palette1 = `tput setaf 0`.

**Comment by danielshahaf** [comment]
> How to change color values ? I mean how they are related to terminal color palette ? For example in${ZSH_HIGHLIGHT_STYLES[unknown-token]:=fg=red,bold}, where the color 'red' is defined ? With my gnome terminal color palette it does not display proper color as I changed the color palette. So I want to understand the relation between the color variables you used and the terminal color palette.

Refer to the zsh manual:
http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#index-terminal-escape-sequences-for-highlighting

> Can we use 'tput setaf ' as it has direct relation with gnome terminal color palette where palette1 = `tput setaf 0`. 

No, we can't use tput because zsh-syntax-highlighting does not write
characters to the terminal.  Zsh itself does.

I suggest that you follow up on zsh-users@zsh.org; this question really
is about zsh's colouring mechanisms, which zsh-syntax-highlighting
simply invokes.
