### ISSUE TITLE
Followup to #415

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#423]
Breaking out the following comment since #415 is already merged and thus can't be reopened:

https://github.com/zsh-users/zsh-syntax-highlighting/pull/415#discussion_r108778847

/cc @docwhat @m0vie

**Comment by docwhat** [comment]
So this is to fix the documentation as per @m0vie's comment?

``` md
If you're using `history-incremental-search-backward` (by default bound to <kbd>Ctrl+R</kbd>
in zsh's emacs keymap) then it works with _zsh version 5.3 and newer_.

If you're using `history-incremental-pattern-search-backward`, then syntax highlighting works
in _zsh 5.3.2 and newer_ due to [a bug in zsh](http://www.zsh.org/cgi-bin/mla/redirect?WORKERNUMBER=40285).

Under zsh 5.2 and older, the zsh-default [underlining][zshzle-Character-Highlighting]
of the matched portion of the buffer remains available, but zsh-syntax-highlighting's
additional highlighting is unavailable.  (Those versions of zsh do not provide
enough information to allow computing the highlighting correctly.)
```

> `history-incremental-search-backward` or `history-incremental-pattern-search-backward` doesn't matter, we don't check for that. Its 5.3.2 and newer in all cases.

Did I misunderstand what the `$ISEARCHMATCH_ACTIVE` does? I thought it was indicating that the `history-incremental-pattern-search-*` was being used?

**Comment by m0vie** [comment]
`ISEARCHMATCH_ACTIVE` is just a flag that indicates that you typed something in `Ctrl-R` that matches. It is unrelated to the widget which is used.

In reality, currently, with the `zsh_highlight__pat_static_bug` condition the check for the flag is redundant, since there are no versions >= 5.3.2 which don't have it. But i'd leave that as it is, should the bug condition ever change.

I simply propose this as the FAQ test:
```
Highlighting the command line during an incremental history search, which is
bound by default to <kbd>Ctrl+R</kbd> in zsh's emacs keymap requires zsh 5.3.2
or newer.
```
