### ISSUE TITLE
Simple way to add fg-italic?

### ISSUE THREAD

**Issue by melMass** [zsh-users/zsh-syntax-highlighting#432]
Hello,

Is there an easy way to add italic ?

zsh **zle** can be tweaked using this command:

```
typeset -AHg fg_italic fg_no_italic
for k in ${(k)color[(I)fg-*]}; do
  fg_italic[${k#fg-}]="$lc${color[standout]};${color[$k]}$rc"
  fg_no_italic[${k#fg-}]="$lc${color[normal]};${color[$k]}$rc"
done
```

But I can't seem to find a way to make zsh-syntax-highlighting aware of that. Any clue ?

Thanks

**Comment by danielshahaf** [comment]
> Hello,
> 
> Is there an easy way to add italic ?
> 
> zsh **zle** can be tweaked using this command:
> 
> ```
> typeset -AHg fg_italic fg_no_italic
> for k in ${(k)color[(I)fg-*]}; do
>   fg_italic[${k#fg-}]="$lc${color[standout]};${color[$k]}$rc"
>   fg_no_italic[${k#fg-}]="$lc${color[normal]};${color[$k]}$rc"
> done
> ```
> 
> But I can't seem to find a way to make zsh-syntax-highlighting aware of that. Any clue ?

The values of `$ZSH_HIGHLIGHT_STYLES` are the same as RHS's of values of the
$region_highlight / $zle_highlight arrays:
http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Character-Highlighting

If you can express italic using that syntax, you can in z-sy-h.  If you
can't, ask zsh to add support for italics :-).

**Comment by Joedang** [comment]
I think the [linked page](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Character-Highlighting) might be slightly misleading as to what's allowed/possible. 

If you play around with different values of `ZSH_HIGHLIGHT_STYLES[comment]='fg=$X'`, and read the part about "fg_start_code (\e[3)", it becomes apparent that when`$X` is a number, it's a 256-color style, NOT a 16-color style. (For example, if `$X` is 9, comments appear light red instead of the default color.) So, things are styled like `\e[38;5;Xm`and NOT `\e[3Xm`. 

So, I figured I could just *inject* an italic style into `$X`. i.e., I could do `fg=9;3` to yield a style of `\e[38;5;9;3m` (light red from the 256-color pallette with an italic style). Nope. I just get the default with no light red color or italic style. If I try to inject things into `zle_highlight` as in `zle_highlight[fg_start_code]='\e[3;3'` or `zle_highlight[fg_end_code]='m\e[3m'`, I get the same result. (Anyways, I would think injecting into `zle_highlight` would make *everything* italic, which isn't even what @melMass or I want.) No amount of quoting or escaping seems to help. 

Inspecting the output (via the `script` command), it looks like Zsh is simply ignoring my modifications to `zle_highlight` and completely omitting any comment styling when I do `ZSH_HIGHLIGHT_STYLES[comment]='fg=9;3'`. 

I get that color codes are kind of gross and this system is meant to isolate the user from that grossness, but it's extremely frustrating that it's "too smart" to allow those of use who understand escape sequences to apply that knowledge.

**Comment by danielshahaf** [comment]
Yes.

**Comment by danielshahaf** [comment]
@ all: About upstream support, see https://zsh.org/workers/48463.

**Comment by ratheesh** [comment]
A new commit in ZSH mainline has been committed to renaming `standout` option as `italics`

Commit ID: `5fdd98552d2cdc7727eb29f75b53da73b39dee4b`

**Comment by danielshahaf** [comment]
> A new commit in ZSH mainline has been committed to renaming `standout` option as `italics`

That's `italic`, singular.

> Commit ID: `5fdd98552d2cdc7727eb29f75b53da73b39dee4b`

https://github.com/zsh-users/zsh/commit/5fdd98552d2cdc7727eb29f75b53da73b39dee4b https://zsh.org/workers/47489

Thanks for the pointer.  That commit didn't change the set of escape codes that can be used, though.

**Comment by lokesh-krishna** [comment]
So, um does it mean that `fg=white,italic` should now work because it doesn't for me on zsh 5.8-1.

**Comment by danielshahaf** [comment]
It means that `fg=white,italic` in 5.9 will do what `fg=white,standout` does in 5.8.

**Comment by FinallyFinancialFreedom** [comment]
> white

means zsh 5.9 still does not support italic font?

**Comment by danielshahaf** [comment]
"Supports italic font" is a property of the terminal emulator, not of the shell.  For instance, xterm supports italic (`print -r -- $'\e[3mhello world\e[0m'` would print that in italic).

What zsh does have is this: https://github.com/zsh-users/zsh/blob/zsh-5.9/Functions/Misc/colors#L17
