### ISSUE TITLE
alias highlighted in green no matter the configuration

### ISSUE THREAD

**Issue by lacygoill** [zsh-users/zsh-syntax-highlighting#565]
- Operating system:     Ubuntu 16.04.5 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux 2.8
 - `$TERM`:              tmux-256color
 - Shell:                zsh 5.6.2-dev-0 (x86_64-pc-linux-gnu)

[This commit](https://github.com/zsh-users/zsh-syntax-highlighting/commit/cb8c736a564e0023a0ef4e7635c0eb4be5eb56a4) seems to have broken the syntax highlighting of aliases in my shell.

They are green no matter what I assign to `ZSH_HIGHLIGHT_STYLES[alias]`.

At the moment, I can reproduce with this minimal `zshrc`:

    alias ls='ls --color=auto'
    [[ -f ${HOME}/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] && \
    . "${HOME}/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
    ZSH_HIGHLIGHT_HIGHLIGHTERS=(main)
    typeset -A ZSH_HIGHLIGHT_STYLES
    ZSH_HIGHLIGHT_STYLES[alias]='fg=red'

The `ls` alias is highlighted in green, even though `ZSH_HIGHLIGHT_STYLES[alias]` should make it red.
I don't think there's anything wrong with the syntax of the command, since this one works fine:

    ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=red'

It highlights a single quoted argument in red.

I had the same issue yesterday, but after commenting out some code/checking out old commits and getting back to master, the issue disappeared. Today, after updating the plugin again, the issue is back, so I don't know how reliable is the previous MWE.

**Comment by phy1729** [comment]
That commit made it so that alias are highlighted as `alias` and whatever the first word of the alias is (in your case `command`). https://github.com/phy1729/zsh-syntax-highlighting/tree/highlight-alias-once changes that to just alias (unless the alias is insane or a loop in which case it also gets `unknown-token`). I have no strong opinion either way.

**Comment by lacygoill** [comment]
Thank you very much for your comment.

I really liked the old behavior because it allowed me to easily distinguish a builtin command from and an alias, which I could expand by pressing `M-e`:

    __expand_aliases() {
      emulate -L zsh
      unset 'functions[___expand_aliases]'
      functions[___expand_aliases]=$BUFFER
      (($+functions[___expand_aliases])) &&
        BUFFER=${functions[___expand_aliases]#$'\t'} &&
        CURSOR=$#BUFFER
    }
    zle -N __expand_aliases
    bindkey '\ee' __expand_aliases

I've tested your fork and your branch `highlight-alias-once`, and it works exactly as before, thank you.
It would be nice if there was an option to get back the old behavior, otherwise I'll try to get used to the new one.

Feel free to close the issue if you disagree.

**Comment by danielshahaf** [comment]
(I commented earlier via email; I assume that'll appear eventually so I won't repost it. In the meantime..)

Let's try to nail down a behaviour spec for aliases.

How about:

1. By default, an alias is highlighted as `alias`, regardless of what it expands to.
2. Nevertheless, an alias that expands to something that would be highlighted as `unknown-token`, such as `alias foo=/no/such/command` and even `alias foo='ls && /no/such/command`, would itself be highlighted as `unknown-token`. (New behaviour)
3. If someone ever wants to highlight aliases differently depending on their expansion, that should be done by adding _one_ style for the alias to $region_highlight.  For example, instead of adding `"1 3 alias" "1 3 command"`, one should add just `"1 3 alias-to-command"` (using the syntax of test expectations).

**Comment by danielshahaf** [comment]
Which implies that the test expectations of `alias-to-dir` and `alias-comment2` are correct as they stood before the recent changes.

**Comment by lacygoill** [comment]
+1 It seems like a sensible spec, I would like it.

**Comment by danielshahaf** [comment]
Thanks for the review! You're welcome to join us on IRC if you like :)

**Comment by danielshahaf** [comment]
I would default to erring on the side of backwards compatibility.

@phy1729 What's the benefit of the new behaviour?  Can it be implemented differently, for example, by highlighting it as `command` then `alias` (opposite order of now), or as `alias-command` which would auto-fallback to `alias` for compatibility?  I'm particularly fond of the latter since it'll make it much easier for theme authors (aka, users, currently) to set the styles.

lacygoill wrote on Mon, 22 Oct 2018 06:15 -0700:

**Comment by phy1729** [comment]
@danielshahaf Branch updated to be either `alias` or `unknown-token`. Found a few bugs as well. If you like I can make a PR out of it.

@lacygoill I forgot earlier, but thank you for the clear, minimal reproducer. It makes things much easier.

**Comment by danielshahaf** [comment]
Sure, may be easier, and numbers are cheap. In `alias-to-dir` I think you removed the wrong line?

(Will look closer later.)
