### ISSUE TITLE
Path checking has no effect

### ISSUE THREAD

**Issue by ChaosCA** [zsh-users/zsh-syntax-highlighting#581]
Everything else seems to work fine but the path checking.

<img width="562" alt="image" src="https://user-images.githubusercontent.com/5280764/48111540-9bc05b00-e217-11e8-8507-2825f245c8dd.png">

^Clearly not a command, picked up on fine.

<img width="562" alt="image" src="https://user-images.githubusercontent.com/5280764/48111574-c5798200-e217-11e8-9b0c-ac4bf0ffef4b.png">

^Not a path but no errors indicated

Is path checking a feature of this project? I’m not sure as it’s not shown in the README.

Thanks!

**Comment by danielshahaf** [comment]
Yes, it's a feature of this project, and it seems to work correctly on your machine: an underlined `.zshrc` is visible in your first screenshot.

**Comment by danielshahaf** [comment]
Words that aren't existing dirent names aren't highlighted specially, even for commands such as `cd` where doing so would be reasonable.

**Comment by ChaosCA** [comment]
I see now that the underlining is denoting that. I suppose I was expecting the fish way and the way that you mark commands as being errors (making it red).

Thanks! You can close this.

**Comment by danielshahaf** [comment]
It's a good idea, though.  The best way to implement it would be to hook into compsys (#10), because then we could do that generally, even for things like `cat foo bar` where `foo` doesn't exist or is a directory.  Implementing it before that would be difficult since we'd have to keep track of which --option flags can take arguments in a separate word (like we do for `sudo`).

I think I'll close this since the additional complexity of hardcoding even just `cd` would not be worth the maintenance effort (keeping in that `builtin cd -P -- foo bar` is valid).
