### ISSUE TITLE
Insallation File says to Add source ~/.zshrc to one's zshrc

### ISSUE THREAD

**Issue by ginglis13** [zsh-users/zsh-syntax-highlighting#598]
i see that this issue has been raised in the past but the instruction is still in the installation readme

**Comment by ginglis13** [comment]
Yes, sorry for not directly referencing the lines I was referring to. You know what, now that I'm re-reading it, I think I just assumed that those lines were to be added to ~/.zshrc rather than run at the command line. My mistake! Closed.

**Comment by danielshahaf** [comment]
I've added `%` prompts to clarify the difference, but I'm tempted to just replace item (3) by "start a new shell for the changes to take effect", since there's no good recommendation to make: `source ${ZDOTDIR-${HOME}}/.zshrc` might not be idempotent and `exec zsh` might lose state and might exec the wrong shell.

**Comment by danielshahaf** [comment]
Thanks for the reviews (= :+1: reactions); pushed 9a06c28.

I don't get email notifications for github reactions; is that configurable on my end? If not, next time please leave a comment as well, lest your feedback be overlooked.
