### ISSUE TITLE
Multiplication in arithmetic expansions highlighted as globbing (was: Arithmetic expansion parsed as command substitution)

### ISSUE THREAD

**Issue by danielshahaf** [zsh-users/zsh-syntax-highlighting#607]
`: $((42))` is parsed as:

```zsh
  '1 1 builtin' # :
  '3 9 default' # $((42))
  '3 9 command-substitution-unquoted' # $((42))
  '3 4 command-substitution-delimiter-unquoted' # $(
  '5 5 reserved-word' # (
  '6 7 unknown-token' # 42
  '8 8 reserved-word' # )
  '9 9 command-substitution-delimiter-unquoted' # )
```

That particular example is an arithmetic expansion, not a command substitution, so the unknown-token error is misplaced.  The reserved-word highlighting for the inner parentheses is also wrong (the inner parentheses aren't zsh syntax tokens here).  Getting this right in general is non-trivial because of things like `$((42); 43)` which are a subshell nested in a command substitution.

**Comment by danielshahaf** [comment]
This also affects the multiplication operator in `$(( 42 * 0 ))`, which is highlighted as [globbing].

**Comment by danielshahaf** [comment]
Retitled to reflect remaining work.

**Comment by danielshahaf** [comment]
The problem (in here and #649 both) is that we can't easily find the `))` that terminate the arithmetic substitution.

If we knew where that was, we'd disable globbing and quote highlighting within the arithmetic substitution.  However, we don't know where it is, and we can't find it in the general case, because arithmetic substitution can contain arbitrary parameter expansion expressions.

Is there some heuristic that wouldn't DTWT in too many cases?  How about, say, "upon seeing `$((`, skip balanced parentheses within the same word until a `))`?

**Comment by phy1729** [comment]
Presumably we should handle the tokens inside an arithmetic substitution as well, so I think we should define a `_zsh_highlight_main_highlighter_highlight_arithmetic` function that `_zsh_highlight_main_highlighter_highlight_argument` and `_zsh_highlight_main_highlighter_highlight_double_quote` call on reaching `$((`. Then `_highlight_arithmetic` can handle the possible nested parenthesis.

Handling `$((...) )` could potentially be done by having `_highlight_arithmetic` return non-zero if there is no matching `))` token and falling back to recursing into `_zsh_highlight_main_highlighter_highlight_list` in that case. Since `_highlight_arithmetic` should return highlights in `$reply` like the other helper functions, failing should have no side effects on highlighting.

**Comment by danielshahaf** [comment]
How could that function be implemented?  Remember that arithmetic substitution undergo double-quoted expansion before being parsed as math, so `s='4*2'; echo $(($s))` prints `8`, and `$(( $(foo) ))` is valid too.  I think that means we have no hope of doing parsing the arithmetic expression in the general case; the best we can do is detect its end.

**Comment by phy1729** [comment]
Something like https://github.com/phy1729/zsh-syntax-highlighting/commit/aeedcacdd071c7532710ff31b0a10d639e723b9d . Doubtlessly has errors and needs quite a few tests, but I think the essence is correct.

**Comment by danielshahaf** [comment]
Seems like it'd DTWT whenever the arithmetic expression would happen to contain two consecutive closing parentheses, e.g., `: $(( ((42)) ))`.

**Comment by phy1729** [comment]
That's why `paren_depth` is checked before the check for `))`.

**Comment by danielshahaf** [comment]
Sorry, misread the diff. I'll look again.

**Comment by danielshahaf** [comment]
LGTM
