### ISSUE TITLE
zsh command prompt hangs when a wildcard character is typed

### ISSUE THREAD

**Issue by rgeorgiev583** [zsh-users/zsh-syntax-highlighting#612]
## Description

After I type a wildcard character for glob patterns (i.e. `*`, `?`, etc), the zsh command prompt simply hangs, and I am unable to type anything until I interrupt the entering of the current command using **Ctrl+C**.  I noticed that there's also a spike in CPU usage until the moment of interruption, after which it is back to normal levels.

According to my observations, the issue appeared after I began using the version of `zsh-syntax-highlighting` from the `master` branch of this repository as an Antigen plugin.  Before that, I had used the latest release (i.e. version `0.6.0`).

## Software versions

* `zsh-syntax-highlighting`: `master` (`7ba4f0f`)
* `zsh --version`: `zsh 5.7.1 (x86_64-pc-linux-gnu)`
* `uname -a`: `Linux pensieve 5.0.7-1-MANJARO #1 SMP PREEMPT Sat Apr 6 08:50:27 UTC 2019 x86_64 GNU/Linux`

**Comment by phy1729** [comment]
Can you attempt to reproduce this starting from `zsh -f` (which ignores your dotfiles)? I suspect it's an option that you have set that isn't being tested for.

**Comment by rgeorgiev583** [comment]
So I started a new shell using `zsh -f`, and then I ran `zgen load zsh-users/zsh-syntax-highlighting` to source the plugin from the `master` of this repo.  As you expected, I couldn't reproduce the issue.  I also cannot reproduce it if I directly source the plugin after `zsh -f`.

It seems that the problem is not in your code, so I'll try inspecting my `.zshrc` more thoroughly in order to find the cause.  Anyway, feel free to close this issue.

**Comment by rgeorgiev583** [comment]
Hmm, I think I found the cause of the problem... it seems that the issue becomes reproducible only after the `BASH_REMATCH` zsh option is enabled.

**Comment by phy1729** [comment]
That's it. Thanks for figuring that out. The issue is https://github.com/zsh-users/zsh-syntax-highlighting/blob/7ba4f0f119495cd95c9811a0afa94cfbe337fdc3/highlighters/main/main-highlighter.zsh#L1098 `MATCH` is not set so `$#MATCH` is 0 and the loop never progresses.

I think the right solution (since `emulate -L zsh` doesn't reset bash_rematch) is to add nobashrematch to https://github.com/zsh-users/zsh-syntax-highlighting/blob/7ba4f0f119495cd95c9811a0afa94cfbe337fdc3/zsh-syntax-highlighting.zsh#L104 (making it `setopt localoptions warncreateglobal nobashrematch`). Looks fixed here with that change.

**Comment by phy1729** [comment]
Since it fixed things for me I've gone ahead and pushed the patch. Please reopen if the change didn't fix things for you.
