### ISSUE TITLE
syntax highlighting doesn't work until certain keys are pressed

### ISSUE THREAD

**Issue by t2nerb** [zsh-users/zsh-syntax-highlighting#738]
**MacOS version: 10.15.4**
**zsh-syntax-highlighting version: 0.7.1**

When typing out a command, syntax highlighting doesn't appear immediately. The only way to get the syntax highlighting to appear is to either: 
1. Press space
2. Press backspace
3. Press enter 

Tiny GIF showing the issue: https://giphy.com/gifs/WRzfHFuxegBhhCYaUo

**Comment by danielshahaf** [comment]
Can you reproduce the problem in `zsh -f`?  (Run that.  You'll get a `hostname% ` prompt.   At that prompt, run `source /path/to/zsh-syntax-highlighting.zsh` by hand, after replacing `/path/to` with the correct value, then type in your test command and check if it's highlighted correctly.)

If not, it'll be due to interaction with some other plugin.  You'll have to check your dotfiles.  (You could also try the feature/redrawhook branch.)

**Comment by t2nerb** [comment]
Ahh, the issue was a new `source` was appended to my `.zshrc`. 

Sourcing it last in my `.zshrc` fixed it for me :facepalm:

**Comment by danielshahaf** [comment]
Thanks for following up.

This might be a bug in that other plugin, actually.  When z-sy-h wraps a widget, it calls a previous user-defined wrapper function, if one was present when z-sy-h was installed.  That other plugin doesn't seem to do that, meaning it must be installed before any other plugins that wraps widgets — which, naturally, isn't composable.  (There can only be one such plugin in any one user's configuration.)

**Comment by bmrejen** [comment]
@t2nerb keep in mind you will have to source zsh-history-substring-search.zsh after zsh-syntax-highlighting if you ever want to use it

**Comment by rootex-** [comment]
> Ahh, the issue was a new `source` was appended to my `.zshrc`.
> 
> Sourcing it last in my `.zshrc` fixed it for me 🤦

thanks, worked for me 🥳
