### ISSUE TITLE
path highlighting is still 'enabled' after being disabled

### ISSUE THREAD

**Issue by nkdmSum** [zsh-users/zsh-syntax-highlighting#755]
I decided to disable path highlighting since it would think that I'm typing a directory instead of a command if they have the same name/start similarly(the command would only turn green once I was done typing it). But disabling it just made it highlight these cases black. That means that normally typing `clear` would go like this: You type `clea` and it would be red. Then you type `r` and it would turn green. But if you have a folder with the name `clear`, it would go *black*(my default colour) for `clea` and then green for `r`. Is there any way to fix this so that it ignores paths entirely?

**Comment by danielshahaf** [comment]
> I decided to disable path highlighting since it would think that I'm typing a directory instead of a command if they have the same name/start similarly(the command would only turn green once I was done typing it).

That would be because you have the AUTO_CD option set.  It is unset by default.  If you don't set it, z-sy-h won't highlight the command word as a path.

> But disabling it just made it highlight these cases black. That means that normally typing `clear` would go like this: You type `clea` and it would be red. Then you type `r` and it would turn green. But if you have a folder with the name `clear`, it would go *black*(my default colour) for `clea` and then green for `r`. Is there any way to fix this so that it ignores paths entirely?

Either go to your terminal emulator's settings and change the default colours (for foreground and/or background), or set the colours of `path` and `path_prefix` explicitly to something you can see.  For example, `fg=white`.

However, you should probably just stop setting the AUTO_CD option, and leave `path` and `path_prefix` at their defaults.

You might be using someone else's configuration.  If so, you might wish to review it to see what other surprises it has in store for you.

**Comment by nkdmSum** [comment]
@danielshahaf I've disabled auto_cd (It looks like it's automatically enabled by my terminal[terminal.app on mac]) by adding `unset AUTO_CD` to my zshrc, but it didn't fix it(although auto_cd doesn't work anymore). I'm not using someone else's configuration.

**Comment by nkdmSum** [comment]
I've solved this by setting the path-highlighting colour to the default colour, so that I wouldn't notice a difference.
