### ISSUE TITLE
Aliases with z expansion shouldn't be invalid

### ISSUE THREAD

**Issue by nomasprime** [zsh-users/zsh-syntax-highlighting#771]
These valid aliases are rending in red:

```zsh
alias b='${(z)BROWSER}'
alias e='${(z)VISUAL:-${(z)EDITOR}}'
alias p='${(z)PAGER}'
```

**Comment by phy1729** [comment]
Boils down to #695 and related to #484, #619, and #716 (`alias a='$NULLCMD'` is red as well).

Basically at present z-sy-h doesn't distinguish between a syntax error and constructs it cannot parse (due to side effects or the parsing code not being written yet).

**Comment by nomasprime** [comment]
Hi @phy1729.

The really weird thing is it was working for me but messing around with my config late at night, rarely a good idea, I broke it. Do you have any idea how that's possible?

The only thing I can think to do is diff all my config.

**Comment by phy1729** [comment]
Perhaps before you had `alias b='$BROWSER'`? The other option is to use functions instead of aliases. Even the completion system seems to give up on parsing through `(z)`, so you wouldn't lose more specific completions with functions.

**Comment by nomasprime** [comment]
After diffing both machines it turns out it was from updating to the latest from 7044c19. If I roll back to this commit, it works again.

**Comment by danielshahaf** [comment]
Back then, an alias was highlighted in green if it existed, so stuff like `x='not a command'; alias a='${(z)x}'` was green.

Nowadays, an alias is replaced with its contents and that's parsed in turn.  That's so if you do `alias x=less` and less(1) happens to not be installed, that'd be highlighted as red.

The caveat is that the code doing the replacing doesn't support parameter expansions other than `$foo` and `${foo}`, with no parameter expansion flags/operators. no history expansion suffixes, and no nesting.  `(z)` specifically could in principle be added — though some care would be required, since its expansion is multiple words — but, given the aforementioned other features that won't be addressed by adding only `${(z)}`, I think it might be much easier in the long run to work with zsh upstream on a way to evaluate a _generic_ parameter expansion expressions without side effects.  The API could be, say:

```zsh
foo=hello bar=(lorem ipsum)
somenewbuiltin '${foo[1]}'
# $?=0
# $REPLY = 'h'
# $reply unset
somenewbuiltin '${(L)bar}'
# $? = 0
# $REPLY unset
# $reply = (foo bar)
somenewbuiltin '${syntax error}'
# $? = 1
# $REPLY unset
# $reply unset
```

**Comment by danielshahaf** [comment]
And of course:

```zsh
somenewbuiltin '${$(pwd)}'
# $? = 1
# $REPLY unset
# $reply unset
```

**Comment by nomasprime** [comment]
Got it. Thanks for the explanation @danielshahaf.

Seems like one step forward, one back, would be really nice to have this feature. I'll always try to help out but my zsh knowledge is fairly middling. Do you know if this has been requested upstream?

**Comment by danielshahaf** [comment]
> Seems like one step forward, one back, would be really nice to have this feature. I'll try to help out but my zsh knowledge is fairly middling. Do you know if this has been requested upstream?

I don't recall upstream discussions about this idea specifically.

As to helping, first of all, welcome aboard!  I'm sure your zsh knowledge is up to par, and in any case, implementing this upstream would involve much more C work than zsh scripting work.

**Comment by nomasprime** [comment]
Thanks 🙂 

Pretty long list of things to do but it's in there.
