### ISSUE TITLE
'$' leading words inherit wrong color?

### ISSUE THREAD

**Issue by browser-bug** [zsh-users/zsh-syntax-highlighting#780]
I'm using [kitty-terminal](https://github.com/kovidgoyal/kitty) and anytime I start typing something with a leading `$` (which happens quite a lot if I need to cd inside a path referenced by an env variable), the syntax highlighting sets the word with the `color0` (that in my case happen to be the same of the background). I've tried it using `urxvt` and in that case it seems to be using `color8` instead. Now, should I open a ticket on the kitty repo page or this might have something to do with the highlighting package itself?

zsh-version: `5.8 (x86_64-ubuntu-linux-gnu)`
z-sy-h-version: `0.8.0-alpha2-dev`

I can put the whole theme config files for each terminal if that may help.

![kitty-2020-11-12_17 43 46](https://user-images.githubusercontent.com/44030022/98969443-232fbb80-250f-11eb-88a4-7bcca5b6c553.gif)
![urxvt-2020-11-12_17 45 04](https://user-images.githubusercontent.com/44030022/98969456-25921580-250f-11eb-9c23-2389427e1080.gif)

**Comment by danielshahaf** [comment]
You haven't mentioned what versions you use, so I'll answer for latest zsh and latest z-sy-h.

> the syntax highlighting sets the word with the `color0` (that in my case happen to be the same of the background). I've tried it using `urxvt` and in that case it seems to be using `color8` instead.

Variable expansions in command position that expand to null are highlighted with the `comment` style, as though by `print -rP %F{black}%Bhelloworld%b%f` — which, if I'm reading [the C code](https://github.com/zsh-users/zsh/blob/d3a6dee9cd7f874fe543a7daf6165b8beee80eea/Src/prompt.c#L1685) correctly, is hardcoded to be color 0.  Plain xterm renders that as grey on black.

Recommend that you set your colour palette so that bold black is readable.  (Personally, I use `xterm` with `XTerm*background: #5c5c35356666` & `XTerm*foreground: #ffffff`, but I'm not entirely happy with the contrast of some black/blue variants to that background colour.  Suggestions welcome, by the way.)

Workaround/Hotfix is to change the value of `ZSH_HIGHLIGHT_STYLES[comment]`.

> Now, should I open a ticket on the kitty repo page or this might have something to do with the highlighting package itself?

Well, I'm not sure they'd consider this a bug — even xterm has unreadable colours in its default colourscheme, and there are compatibility/interoperability considerations — but can't hurt to ask.

**Comment by browser-bug** [comment]
I'm sorry I forgot to mention. I've updated the question. I'd like to stick to my current terminal theme honestly, so I think the hotfix will do for now, thanks! Is it viable to change the value from `.zshrc`?

> Well, I'm not sure they'd consider this a bug — even xterm has unreadable colours in its default colourscheme, and there are compatibility/interoperability considerations — but can't hurt to ask.
I'll try ask and get back to this in case.

**Comment by browser-bug** [comment]
So, for anyone experiencing this issue, just add this into your `.zshrc` and make sure it's **after** the `zsh-syntax-highlighting.zsh` file sourcing.

```
if [[ $TERM == "xterm-kitty" ]]; then
    ZSH_HIGHLIGHT_STYLES[comment]="fg=whatever_color,bold"
fi

```

**Comment by danielshahaf** [comment]
All looks good. Cheers!

**Comment by EdwarDu** [comment]
> So, for anyone experiencing this issue, just add this into your `.zshrc` and make sure it's **after** the `zsh-syntax-highlighting.zsh` file sourcing.
> 
> ```
> if [[ $TERM == "xterm-kitty" ]]; then
>     ZSH_HIGHLIGHT_STYLES[comment]="fg=whatever_color,bold"
> fi
> ```

urxvt has the same issue, I just add it without the if condition :D

**Comment by MetalDozer** [comment]
nano .config/kitty/kitty.conf

background #00004f 
foreground #55ff00
color0 #aa007f // color of the $VARIABLES

you can chage colors this easy way.
the problem was backgroud and color0 black.
